name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Set up Python
        uses: actions/setup-python@v2.3.0
      - name: Install
        run: pip install flake8 pylint
      - name: Run tests
        run: make test
